# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

org1 = Organizer.create(email: "watson@me.com", password_digest: "password123")
org2 = Organizer.create(email: "philomena@me.com", password_digest: "password123")
org3 = Organizer.create(email: "christ@me.com", password_digest: "password123")

Forage.create([
  {forage_level: "small", orgs_code: "TEAMBUILDER-1-John", organizer_id: 1},
  {forage_level: "small", orgs_code: "TEAMBUILDER-1-Tom", organizer_id: 1},
  {forage_level: "small", orgs_code: "TEAMBUILDER-1-Bob", organizer_id: 1},
  {forage_level: "medium", orgs_code: "PARTY-1-Quin", organizer_id: 2},
  {forage_level: "medium", orgs_code: "PARTY-1-Sally", organizer_id: 2},
  {forage_level: "medium", orgs_code: "PARTY-1-Daisy", organizer_id: 2},
  {forage_level: "large", orgs_code: "WEEKEND-1-Lyd", organizer_id: 3},
  {forage_level: "large", orgs_code: "WEEKEND-1-Billy", organizer_id: 3},
  {forage_level: "large", orgs_code: "WEEKEND-1-Lady", organizer_id: 3}
  ])

Answer.create([
  {answer: "google.com", correct: "grade-pending", forage_id: 1},
  {answer: "google.com", correct: "grade-pending", forage_id: 1},
  {answer: "google.com", correct: "grade-pending", forage_id: 1},
  {answer: "google.com", correct: "grade-pending", forage_id: 1},
  {answer: "google.com", correct: "grade-pending", forage_id: 1},
  {answer: "google.com", correct: "grade-pending", forage_id: 1},
  {answer: "google.com", correct: "grade-pending", forage_id: 2},
  {answer: "google.com", correct: "grade-pending", forage_id: 2},
  {answer: "google.com", correct: "grade-pending", forage_id: 2},
  {answer: "google.com", correct: "grade-pending", forage_id: 2},
  {answer: "google.com", correct: "grade-pending", forage_id: 2},
  {answer: "google.com", correct: "grade-pending", forage_id: 2},
  {answer: "google.com", correct: "grade-pending", forage_id: 3},
  {answer: "google.com", correct: "grade-pending", forage_id: 3},
  {answer: "google.com", correct: "grade-pending", forage_id: 3},
  {answer: "google.com", correct: "grade-pending", forage_id: 3},
  {answer: "google.com", correct: "grade-pending", forage_id: 3},
  {answer: "google.com", correct: "grade-pending", forage_id: 3},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 4},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 5},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 6},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 7},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 8},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  {answer: "google.com", correct: "grade-pending", forage_id: 9},
  ])

Smallclue.create([
  {clue_text: "Find a triptych. Now. Find a triptych with an image of 'Saint Babbara'",
   clue_answer: "The Trinity Adored by All Saints - Spanish Painter",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP200558.jpg",
   clue_gallery: "626",
   forage_level: "small"
 },
 {clue_text: "Show me a man, cast mainly in shadow, who is trying to see better",
  clue_answer: "Man with a magnifying glass - Rembrandt",
  clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP145909.jpg",
  clue_gallery: "634",
  forage_level: "small"
},
{clue_text: "Before (or after, I guess) I married my mother, I gazed longingly into the eyes of this mythical creature",
 clue_answer: "Oedipus and the Sphinx - Gustave Moreau",
 clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP-14201-023.jpg",
 clue_gallery: "800",
 forage_level: "small"
},
{clue_text: "I'm the mouth that feeds of a river in Franche-Comté",
 clue_answer: "The Source - Gustave Courbet",
 clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT1964.jpg",
 clue_gallery: "812",
 forage_level: "small"
},
{clue_text: "Monochromatic patriotism, behold",
 clue_answer: "White Flag - Jasper Johns",
 clue_image_url: "https://images.metmuseum.org/CRDImages/ma/web-large/DT4325.jpg",
 clue_gallery: "924",
 forage_level: "small"
},
{clue_text: "The questions is: where are they going, Roy?",
 clue_answer: "Stepping Out - Roy Lichtenstein",
 clue_image_url: "https://images.metmuseum.org/CRDImages/ma/web-large/DP368173.jpg",
 clue_gallery: "924",
 forage_level: "small"
},
{clue_text: "I'm a navel gazing man although, I have no navel to gaze at. Maybe that's why I look so ashamed",
 clue_answer: "A Hypocrite and a Slanderer - Franz Xaver Messerschmidt",
 clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DP225514.jpg",
 clue_gallery: "548",
 forage_level: "small"
},
{clue_text: "Two words that start with 'P' are Pink and Potpourri. Take a picture, but don't ever put this in your house",
 clue_answer: "Potpourri Vase - Sèvres Manufactory",
 clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DP149951.jpg",
 clue_gallery: "529",
 forage_level: "small"
},
{clue_text: "Did she take the dragon’s head or did it bite off her arm first?",
 clue_answer: "Saint Margaret of Antioch",
 clue_image_url: "https://images.metmuseum.org/CRDImages/md/original/DP144443.jpg",
 clue_gallery: "305",
 forage_level: "small"
},
{clue_text: "Not all doors are real. Some people believed that false doors represent the ability of the living to contact the dead. Find a false door.",
 clue_answer: "The tomb of Perneb - Alter, False Door",
 clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DP108489.jpg",
 clue_gallery: "100",
 forage_level: "small"
},
{clue_text: "In a room full of heads, three bodies kneel with an offering- but one faceless body among them does not. Find her.",
 clue_answer: "Large Seated Statue of Hatshepsut",
 clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/21P_FIG3A3_3R3.jpg",
 clue_gallery: "115",
 forage_level: "small"
},
{clue_text: "Where does the crocodile guard the water?
Hint: take a seat or pray here. But don't touch anything.",
 clue_answer: "A crocodile at The Temple of Dendur",
 clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DP244278.jpg",
 clue_gallery: "131",
 forage_level: "small"
},
{clue_text: "I'm honest. And I'm dead. Some actors just hated me...",
 clue_answer: "Abraham Lincoln - Bust",
 clue_image_url: "https://images.metmuseum.org/CRDImages/ap/original/270783.jpg",
 clue_gallery: "774",
 forage_level: "small"
},
{clue_text: "I'm not American, per say, but I do have a naval arsenal, even if it's just three-pronged. #HipsterBeardNeedsCutting",
 clue_answer: "The Return of Neptune - John Singleton Copley",
 clue_image_url: "https://images.metmuseum.org/CRDImages/ap/original/DT201337.jpg",
 clue_gallery: "751",
 forage_level: "small"
},
{clue_text: "A lot of Buddhas overlook these wooden benches.",
 clue_answer: "Buddha of Medicine Bhaishajyaguru (Yaoshi fo)",
 clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DT227320.jpg",
 clue_gallery: "206",
 forage_level: "small"
},
{clue_text: "If you’re not too judge-y, you might catch some sun in a court that babbles loudly. Don't feed the fish, though.",
 clue_answer: "The Astor Chinese Garden Court",
 clue_image_url: "https://images.metmuseum.org/CRDImages/as/web-large/DSvh1_816.jpg",
 clue_gallery: "217",
 forage_level: "small"
},
{clue_text: "Some horses are studious and have elephantine buddies. You might be green with envy if they weren't already.",
 clue_answer: "Horse carrying books",
 clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DP267493.jpg",
 clue_gallery: "222",
 forage_level: "small"
},
{clue_text: "I'd be relieved to know that you found a room with guardians at the door and walls, some with hooves, and some with beaks. Show me a beaked guardian with a purse.",
 clue_answer: "Relief panel - from the Northwest Palace at Nimrud",
 clue_image_url: "https://images.metmuseum.org/CRDImages/an/original/DP375422.jpg",
 clue_gallery: "401",
 forage_level: "small"
}
  ])

Mediumclue.create([
  {clue_text: "Find a triptych. Now. Find a triptych with an image of 'Saint Babbara'",
   clue_answer: "The Trinity Adored by All Saints - Spanish Painter",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP200558.jpg",
   clue_gallery: "626",
   forage_level: "medium"
  },
  {clue_text: "Indiana Jones doesn't care for these animals, and apparently neither does Vermeer. Or maybe he's ok with them- it is an allegory after all. What did Vermeer seemingly lay to waste?
    Hint: it was with a stone...",
   clue_answer: "Allegory of the Catholic Faith - Johannes Vermeer (Detail of snake in painting)",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP145924.jpg",
   clue_gallery: "632",
   forage_level: "medium"
  },
  {clue_text: "Show me a man, cast mainly in shadow, who is trying to see better",
   clue_answer: "Man with a magnifying glass - Rembrandt",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP145909.jpg",
   clue_gallery: "634",
   forage_level: "medium"
  },
  {clue_text: "Before (or after, I guess) I married my mother, I gazed longingly into the eyes of this mythical creature",
   clue_answer: "Oedipus and the Sphinx - Gustave Moreau",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP-14201-023.jpg",
   clue_gallery: "800",
   forage_level: "medium"
  },
  {clue_text: "I'm the mouth that feeds of a river in Franche-Comté",
   clue_answer: "The Source - Gustave Courbet",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT1964.jpg",
   clue_gallery: "812",
   forage_level: "medium"
  },
  {clue_text: "Leave it to the MET to fill a room almost exclusively with paintings by two artists just to play up their rivalry. Find the row of vessels neither of them painted.",
   clue_answer: "Fishing Boats, Collioure - André Derain",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ma/web-large/ma1982.179.29.jpg",
   clue_gallery: "830",
   forage_level: "medium"
  },
  {clue_text: "Monochromatic patriotism, behold",
   clue_answer: "White Flag - Jasper Johns",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ma/web-large/DT4325.jpg",
   clue_gallery: "924",
   forage_level: "medium"
  },
  {clue_text: "I'm a navel gazing man although, I have no navel to gaze at. Maybe that's why I look so ashamed",
   clue_answer: "A Hypocrite and a Slanderer - Franz Xaver Messerschmidt",
   clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DP225514.jpg",
   clue_gallery: "548",
   forage_level: "medium"
  },
  {clue_text: "Two words that start with 'P' are Pink and Potpourri. Take a picture, but don't ever put this in your house",
   clue_answer: "Potpourri Vase - Sèvres Manufactory",
   clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DP149951.jpg",
   clue_gallery: "529",
   forage_level: "medium"
  },
  {clue_text: "Did she take the dragon’s head or did it bite off her arm first?",
   clue_answer: "Saint Margaret of Antioch",
   clue_image_url: "https://images.metmuseum.org/CRDImages/md/original/DP144443.jpg",
   clue_gallery: "305",
   forage_level: "medium"
  },
  {clue_text: "Not all doors are real. Some people believed that false doors represent the ability of the living to contact the dead. Find a false door.",
   clue_answer: "The tomb of Perneb - Alter, False Door",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DP108489.jpg",
   clue_gallery: "100",
   forage_level: "medium"
  },
  {clue_text: "On The South Wall you'll find a horned goat under a bird.",
   clue_answer: "Tomb Chapel of Raemkai: South Wall",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DT270028.jpg",
   clue_gallery: "102",
   forage_level: "medium"
  },
  {clue_text: "Wah didn't manage to go to bed without proper attire. What was the last thing Wah wore?",
   clue_answer: "Wah's Jewelry",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/40.3.18.JPG",
   clue_gallery: "105",
   forage_level: "medium"
  },
  {clue_text: "In a room full of heads, three bodies kneel with an offering- but one faceless body among them does not. Find her.",
   clue_answer: "Large Seated Statue of Hatshepsut",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/21P_FIG3A3_3R3.jpg",
   clue_gallery: "115",
   forage_level: "medium"
  },
  {clue_text: "Where does the crocodile guard the water?
    Hint: take a seat or pray here. But don't touch anything.",
   clue_answer: "A crocodile at The Temple of Dendur",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DP244278.jpg",
   clue_gallery: "131",
   forage_level: "medium"
  },
  {clue_text: "I'm honest. And I'm dead. Some actors just hated me...",
   clue_answer: "Abraham Lincoln - Bust",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ap/original/270783.jpg",
   clue_gallery: "774",
   forage_level: "medium"
  },
  {clue_text: "He rides a horse, and they're both really tired, so I guess they've been doing it for a while.",
   clue_answer: "End of the Trail - James Earle Fraser",
   clue_image_url: "https://www.metmuseum.org/toah/images/hb/hb_2010.73.jpg",
   clue_gallery: "765",
   forage_level: "medium"
  },
  {clue_text: "I'm not American, per say, but I do have a naval arsenal, even if it's just three-pronged. #HipsterBeardNeedsCutting",
   clue_answer: "The Return of Neptune - John Singleton Copley",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ap/original/DT201337.jpg",
   clue_gallery: "751",
   forage_level: "medium"
  },
  {clue_text: "A lot of Buddhas overlook these wooden benches.",
   clue_answer: "Buddha of Medicine Bhaishajyaguru (Yaoshi fo)",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DT227320.jpg",
   clue_gallery: "206",
   forage_level: "medium"
  },
  {clue_text: "If you’re not too judge-y, you might catch some sun in a court that babbles loudly. Don't feed the fish, though.",
   clue_answer: "The Astor Chinese Garden Court",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/web-large/DSvh1_816.jpg",
   clue_gallery: "217",
   forage_level: "medium"
  },
  {clue_text: "A great Qing once said, 'Some art can be worn. Even if it's covered in cranes.'",
   clue_answer: "Woman’s coat with crane medallions - Qing dynasty",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DP226472.jpg",
   clue_gallery: "220",
   forage_level: "medium"
  },
  {clue_text: "Some horses are studious and have elephantine buddies. You might be green with envy if they weren't already.",
   clue_answer: "Horse carrying books",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DP267493.jpg",
   clue_gallery: "222",
   forage_level: "medium"
  },
  {clue_text: "For someone with 8 arms and a dead demon under their feet, she seem to be in need of a head. Maybe she could use a cup of Java...",
   clue_answer: "The Goddess Durga Victorious over the Buffalo Demon, Mahisha (Mahishasuramardini)",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/1988_160.jpg",
   clue_gallery: "247",
   forage_level: "medium"
  },
  {clue_text: "Even Vishnu needed a ride... Find a gilded example of how Vishnu got around.",
   clue_answer: "Vishnu Riding on Garuda - Nepal (Gilt copper repoussé)",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DP306132.jpg",
   clue_gallery: "252",
   forage_level: "medium"
  },
  {clue_text: "Hey pig, you're made of stucco. Its buddy, the bear, would probably like some honey, if he's anything like Winnie. It came from the Sasanian period.",
   clue_answer: "Wall panel with a charging boar - Mesopotamia, Ctesiphon",
   clue_image_url: "https://images.metmuseum.org/CRDImages/an/original/DP-1093-001.jpg",
   clue_gallery: "405",
   forage_level: "medium"
  },
  {clue_text: "I'd be relieved to know that you found a room with guardians at the door and walls, some with hooves, and some with beaks. Show me a beaked guardian with a purse.",
   clue_answer: "Relief panel - from the Northwest Palace at Nimrud",
   clue_image_url: "https://images.metmuseum.org/CRDImages/an/original/DP375422.jpg",
   clue_gallery: "401",
   forage_level: "medium"
  }
  ])

Largeclue.create([
  {clue_text: "Find a triptych. Now. Find a triptych with an image of 'Saint Babbara'",
   clue_answer: "The Trinity Adored by All Saints - Spanish Painter",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP200558.jpg",
   clue_gallery: "626",
   forage_level: "large"
 },
  {clue_text: "Indiana Jones doesn't care for these animals, and apparently neither does Vermeer. Or maybe he's ok with them- it is an allegory after all. What did Vermeer seemingly lay to waste?
    Hint: it was with a stone...",
   clue_answer: "Allegory of the Catholic Faith - Johannes Vermeer (Detail of snake in painting)",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP145924.jpg",
   clue_gallery: "632",
   forage_level: "large"
  },
  {clue_text: "Find de Witte’s dog. What does it seem to think of the church?",
   clue_answer: "Interior of the Oude Kerk, Delft - Emanuel de Witte",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP145954.jpg",
   clue_gallery: "632",
   forage_level: "large"
 },
  {clue_text: "Show me a man, cast mainly in shadow, who is trying to see better",
   clue_answer: "Man with a magnifying glass - Rembrandt",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP145909.jpg",
   clue_gallery: "634",
   forage_level: "large"
  },
  {clue_text: "Writ above me is 'Hvmana Vana'. 'All I want for Christmas' was probably written about this person.",
   clue_answer: "Vanitas Still Life - Jacques de Gheyn II",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP143209.jpg",
   clue_gallery: "635",
   forage_level: "large"
 },
  {clue_text: "Before (or after, I guess) I married my mother, I gazed longingly into the eyes of this mythical creature",
   clue_answer: "Oedipus and the Sphinx - Gustave Moreau",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP-14201-023.jpg",
   clue_gallery: "800",
   forage_level: "large"
  },
  {clue_text: "Hold your noses, my white shoes might smell more than the onions next them.",
   clue_answer: "The Spanish Singer - Édouard Manet",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/dp130799.jpg",
   clue_gallery: "810",
   forage_level: "large"
 },
  {clue_text: "I'm the mouth that feeds of a river in Franche-Comté",
   clue_answer: "The Source - Gustave Courbet",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT1964.jpg",
   clue_gallery: "812",
   forage_level: "large"
  },
  {clue_text: "I am the most relaxed of men in my green pants, considering the commotion happening right next to me.",
   clue_answer: "The Horse Fair",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT44.jpg",
   clue_gallery: "812",
   forage_level: "large"
 },
  {clue_text: "Leave it to the MET to fill a room almost exclusively with paintings by two artists just to play up their rivalry. Find the row of vessels neither of them painted.",
   clue_answer: "Fishing Boats, Collioure - André Derain",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ma/web-large/ma1982.179.29.jpg",
   clue_gallery: "830",
   forage_level: "large"
  },
  {clue_text: "If you had a, like, totally cool or whatever, baby in Brooklyn or the UWS (with that new money), you'd probably put this over it's crib. You'd be a terrible parent, but you'd do it.",
   clue_answer: "Mobile - Alexander Calder",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ma/web-large/sf%2042.176a-d.jpg",
   clue_gallery: "920",
   forage_level: "large"
 },
  {clue_text: "Monochromatic patriotism, behold",
   clue_answer: "White Flag - Jasper Johns",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ma/web-large/DT4325.jpg",
   clue_gallery: "924",
   forage_level: "large"
  },
  {clue_text: "Its title implies some wind, but this american abstraction barely little resemblance.",
   clue_answer: "Whirlirama - Sam Gilliam",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ma/web-large/DP328387_cropped.jpg",
   clue_gallery: "923",
   forage_level: "large"
 },
  {clue_text: "A young ( for ‘The Elder’), busty Medici, you see.",
   clue_answer: "Cosimo I de' Medici (1519–1574), Duke of Florence - Baccio Bandinelli",
   clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DP242104.jpg",
   clue_gallery: "503",
   forage_level: "large"
  },
  {clue_text: "I'm a navel gazing man although, I have no navel to gaze at. Maybe that's why I look so ashamed",
   clue_answer: "A Hypocrite and a Slanderer - Franz Xaver Messerschmidt",
   clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DP225514.jpg",
   clue_gallery: "548",
   forage_level: "large"
 },
  {clue_text: "The hottest season, she is cast in bronze.",
   clue_answer: "Summer - Aristide Maillol",
   clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DP144397.jpg",
   clue_gallery: "548",
   forage_level: "large"
  },
  {clue_text: "Two words that start with 'P' are Pink and Potpourri. Take a picture, but don't ever put this in your house",
   clue_answer: "Potpourri Vase - Sèvres Manufactory",
   clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DP149951.jpg",
   clue_gallery: "529",
   forage_level: "large"
 },
  {clue_text: "Sip a drink from me on the beach, even if it’s a cloudy day, you’ll see the sun’s rays can find a way.",
   clue_answer: "Chalice à Soleil - France, Paris",
   clue_image_url: "https://images.metmuseum.org/CRDImages/es/original/DT571.jpg",
   clue_gallery: "544",
   forage_level: "large"
  },
  {clue_text: "Did she take the dragon’s head or did it bite off her arm first?",
   clue_answer: "Saint Margaret of Antioch",
   clue_image_url: "https://images.metmuseum.org/CRDImages/md/original/DP144443.jpg",
   clue_gallery: "305",
   forage_level: "large"
 },
  {clue_text: "Not all doors are real. Some people believed that false doors represent the ability of the living to contact the dead. Find a false door.",
   clue_answer: "The tomb of Perneb - Alter, False Door",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DP108489.jpg",
   clue_gallery: "100",
   forage_level: "large"
  },
  {clue_text: "On The South Wall you'll find a horned goat under a bird.",
   clue_answer: "Tomb Chapel of Raemkai: South Wall",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DT270028.jpg",
   clue_gallery: "102",
   forage_level: "large"
 },
  {clue_text: "An official of Amenhotep III looks to have spite his  face, though it is unlikely the work of his own hand. Find this face.",
   clue_answer: "Head of An Official - reign of Amenhotep III",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/66.99.31_01.jpg",
   clue_gallery: "119",
   forage_level: "large"
  },
  {clue_text: "Wah didn't manage to go to bed without proper attire. What was the last thing Wah wore?",
   clue_answer: "Wah's Jewelry",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/40.3.18.JPG",
   clue_gallery: "105",
   forage_level: "large"
 },
  {clue_text: "In a room full of heads, three bodies kneel with an offering- but one faceless body among them does not. Find her.",
   clue_answer: "Large Seated Statue of Hatshepsut",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/21P_FIG3A3_3R3.jpg",
   clue_gallery: "115",
   forage_level: "large"
  },
  {clue_text: "A jackal balances a scale. He's more than a doodle on loose leaf. He's only helping someone 'Coming Forth By Day'.",
   clue_answer: "Book of the Dead for the Singer of Amun, Nany",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DT11633.jpg",
   clue_gallery: "126",
   forage_level: "large"
 },
  {clue_text: "Where does the crocodile guard the water?
    Hint: take a seat or pray here. But don't touch anything.",
   clue_answer: "A crocodile at The Temple of Dendur",
   clue_image_url: "https://images.metmuseum.org/CRDImages/eg/original/DP244278.jpg",
   clue_gallery: "131",
   forage_level: "large"
  },
  {clue_text: "I'm honest. And I'm dead. Some actors just hated me...",
   clue_answer: "Abraham Lincoln - Bust",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ap/original/270783.jpg",
   clue_gallery: "774",
   forage_level: "large"
 },
  {clue_text: "He rides a horse, and they're both really tired, so I guess they've been doing it for a while.",
   clue_answer: "End of the Trail - James Earle Fraser",
   clue_image_url: "https://www.metmuseum.org/toah/images/hb/hb_2010.73.jpg",
   clue_gallery: "765",
   forage_level: "large"
  },
  {clue_text: "A horse is a horse, of course, of course- and this Park scene has many. Not to mention how South American this artist's middle name is.",
   clue_answer: "Central Park - Maurice Brazil Prendergast",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ap/original/DT9345.jpg",
   clue_gallery: "772",
   forage_level: "large"
 },
  {clue_text: "I'm not American, per say, but I do have a naval arsenal, even if it's just three-pronged. #HipsterBeardNeedsCutting",
   clue_answer: "The Return of Neptune - John Singleton Copley",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ap/original/DT201337.jpg",
   clue_gallery: "751",
   forage_level: "large"
  },
  {clue_text: "If my kids were American and British respectively, they'd have been named after a boxer Creed, and a Welsh Princess.",
   clue_answer: "Latona and Her Children, Apollo and Diana - William Henry Rinehart",
   clue_image_url: "https://images.metmuseum.org/CRDImages/ap/original/05.12.jpg",
   clue_gallery: "703",
   forage_level: "large"
 },
  {clue_text: "A lot of Buddhas overlook these wooden benches.",
   clue_answer: "Buddha of Medicine Bhaishajyaguru (Yaoshi fo)",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DT227320.jpg",
   clue_gallery: "206",
   forage_level: "large"
  },
  {clue_text: "If you’re not too judge-y, you might catch some sun in a court that babbles loudly. Don't feed the fish, though.",
   clue_answer: "The Astor Chinese Garden Court",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/web-large/DSvh1_816.jpg",
   clue_gallery: "217",
   forage_level: "large"
 },
  {clue_text: "In the lonesome solitude of fallen ﬂowers
                a bird cries in the mountains;
                Among lush green willows
                a man crosses a stream.",
   clue_answer: "Lush Green Willows and A Solitary Path through Cold Mountains - Yosa Buson",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/web-large/L_2017_51_1_2_sr1_001_sf.jpg",
   clue_gallery: "227",
   forage_level: "large"
  },
  {clue_text: "A great Qing once said, 'Some art can be worn. Even if it's covered in cranes.'",
   clue_answer: "Woman’s coat with crane medallions - Qing dynasty",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DP226472.jpg",
   clue_gallery: "220",
   forage_level: "large"
 },
  {clue_text: "Some horses are studious and have elephantine buddies. You might be green with envy if they weren't already.",
   clue_answer: "Horse carrying books",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DP267493.jpg",
   clue_gallery: "222",
   forage_level: "large"
  },
  {clue_text: "Khmer temples needed stone guards too. This one has a lion. Find the lion’s mane.",
   clue_answer: "Guardian Lion - Cambodia or Thailand",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/1979_406.jpg",
   clue_gallery: "249",
   forage_level: "large"
 },
  {clue_text: "For someone with 8 arms and a dead demon under their feet, she seem to be in need of a head. Maybe she could use a cup of Java...",
   clue_answer: "The Goddess Durga Victorious over the Buffalo Demon, Mahisha (Mahishasuramardini)",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/1988_160.jpg",
   clue_gallery: "247",
   forage_level: "large"
  },
  {clue_text: "Even Vishnu needed a ride... Find a gilded example of how Vishnu got around.",
   clue_answer: "Vishnu Riding on Garuda - Nepal (Gilt copper repoussé)",
   clue_image_url: "https://images.metmuseum.org/CRDImages/as/original/DP306132.jpg",
   clue_gallery: "252",
   forage_level: "large"
 },
  {clue_text: "Find a piece of paper with an Akbarian lion relaxing in some bamboo with some birds.",
   clue_answer: "Lion at Rest",
   clue_image_url: "https://images.metmuseum.org/CRDImages/is/original/DP246516.jpg",
   clue_gallery: "463",
   forage_level: "large"
  },
  {clue_text: "Hey pig, you're made of stucco. Its buddy, the bear, would probably like some honey, if he's anything like Winnie. It came from the Sasanian period.",
   clue_answer: "Wall panel with a charging boar - Mesopotamia, Ctesiphon",
   clue_image_url: "https://images.metmuseum.org/CRDImages/an/original/DP-1093-001.jpg",
   clue_gallery: "405",
   forage_level: "large"
  },
  {clue_text: "I'd be relieved to know that you found a room with guardians at the door and walls, some with hooves, and some with beaks. Show me a beaked guardian with a purse.",
   clue_answer: "Relief panel - from the Northwest Palace at Nimrud",
   clue_image_url: "https://images.metmuseum.org/CRDImages/an/original/DP375422.jpg",
   clue_gallery: "401",
   forage_level: "large"
  }
  ])
